### PR TITLE
Bump EDC version to 20221018

### PR DESCRIPTION
**Pull request by ndr-brt**
### What

Bump EDC version to from 20221006 to 20221018.

### Notes
Doing this, the follow commits from EDC will be integrated, with the details of the breaking changes.
In **bold** the commits that actually bring value to C-X

- 2022-10-17 13:52 +0200 o chore: use TestSummary plugin from repositories (#2079)
- 2022-10-17 11:40 +0200 o chore(deps): untangle dependencies (#2098)
- 2022-10-14 15:24 +0200 o docs: add decision record for naming conventions (#2067)
- 2022-10-14 11:25 +0200 o refactor(iam): remove unused dummy-credentials-verifier (#2095)
- 2022-10-14 09:17 +0200 o feat(build): adds manifest files as maven artifacts (#2071)
- 2022-10-13 11:13 +0200 o chore(github): remove checklist from issue template (#2092)
- **2022-10-13 10:59 +0200 o feat(api): add `POST` endpoint to all APIs (#2084)**
- 2022-10-13 08:32 +0200 o docs: remove Docsify related files (#2063)
- 2022-10-13 06:31 +0000 o fix(tests): change IntegrationTest annotation target from TYPE to ANNOTATION_TYPE (#2086)
- 2022-10-12 13:29 +0200 o chore: move ModuleNames plugin out, adapt build source (#2076)
- 2022-10-12 13:28 +0200 o feat(gcs): add provisioner for GoogleCloudStorage (#2038)
- 2022-10-12 13:21 +0200 o docs(adoption): add EDC extension for AAS as known friend (#2070)
- 2022-10-12 11:09 +0200 o chore(ids): remove IdsDescriptorService (#2080)
- **2022-10-12 09:12 +0200 o fix(validation): avoid policy evaluation on consumer side after agreement (#2068)**
- 2022-10-12 08:45 +0200 o chore: update multiple GH action versions (#2078)
- **2022-10-10 18:05 +0200 o feat(api): add a `POST` endpoint to request the catalog (#2060)**
- 2022-10-10 16:51 +0200 o fix(ContractOffer): add asset not null check when building a ContractOffer (#2053)
- **2022-10-10 13:34 +0200 o feat: Stream over ResultSet on sql queries (#2041)**
- 2022-10-10 09:55 +0200 o chore: set output dir of the autodoc plugin (#2065)
- 2022-10-10 08:31 +0200 o docs: document BOM usages (#2061)
- 2022-10-10 08:30 +0200 o build(deps): bump json-unit from 2.35.0 to 2.36.0 (#2066)
- 2022-10-08 12:04 +0200 o fix(transferprocessApi): add id field in DataRequestDTO  (#2056)
- 2022-10-07 15:14 +0200 o build(deps): bump json-unit-json-path from 2.35.0 to 2.36.0 (#2049)
- 2022-10-07 15:12 +0200 o docs: clean up CODEOWNERS (#2057)
- **2022-10-07 15:12 +0200 o fix: use the `range` to limit offers, not definitions (#2018)**
- 2022-10-07 13:41 +0200 o build(deps): bump json-unit-assertj from 2.35.0 to 2.36.0 (#2048)
- 2022-10-07 13:40 +0200 o build(deps): bump json-unit from 2.35.0 to 2.36.0 (#2050)
- 2022-10-07 13:38 +0200 o fix: use IdsId as type for connector ID (#2031)
- **2022-10-07 11:07 +0200 o build(deps): bump azure and aws dependency version to the last releases (#2055)**
- 2022-10-07 06:56 +0200 o feat(DataSourceRegistry): provides a default impl for DataSourceRegistry (#2047)
- 2022-10-06 08:11 +0200 o chore(ContractOffer): remove field assetId (#2046)
  - *API breaking change but it's a removal of a field that actually was always null so nothing disruptive*

### CODE REVIEW

**Comment by denisneuling** [comment]
Hi @ndr-brt and many thanks for your PR. 
Is it urgent to get this merged? - Since there are lots of changes I'd prefer to test this more extensively, although our business-tests pass. Would it be possible to postpone this to be merged until we're crystal clear no existing functionality breaks? 

<sub>Denis Neuling <denis.neuling@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by florianrusch-zf** [comment]
@ndr-brt one question recarding this:

> - 2022-10-06 08:11 +0200 o chore(ContractOffer): remove field assetId (#2046)
>   - API breaking change but it's a removal of a field that actually was always null so nothing disruptive

If the removed field will be send to the EDC, will it be simply ignored or will we receive a 400 bad request from the EDC?

**Comment by ndr-brt** [comment]
> Hi @ndr-brt and many thanks for your PR.
> Is it urgent to get this merged? - Since there are lots of changes I'd prefer to test this more extensively, although our business-tests pass. Would it be possible to postpone this to be merged until we're crystal clear no existing functionality breaks?

Not urgent, it was pretty much to provide the catalog pagination and the policy validation on consumer side bug fixes, anyway what's the process for testing an upstream update like this?



> @ndr-brt one question recarding this:
> 
> > * 2022-10-06 08:11 +0200 o chore(ContractOffer): remove field assetId (#2046)
> >   
> >   * API breaking change but it's a removal of a field that actually was always null so nothing disruptive
> 
> If the removed field will be send to the EDC, will it be simply ignored or will we receive a 400 bad request from the EDC?

Ignored, as [the `TypeManager` is configured to ignore unknown properties](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/c33afe97e763d24b1e831dfe3038a0deb4f55a39/spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/TypeManager.java#L50)

**Comment by DominikPinsel** [comment]
Thank you a lot for the contribution :) as release 0.1.3 is done, we can now merge this

**Review by DominikPinsel — APPROVED** [review]

**Pull request merged**
