### PR TITLE
Allow vault access via certificate from secret

### PR DESCRIPTION
**Pull request by florianrusch-zf**
Open ToDo's:
- Add documentation
  - Creating a cert
  - Configure azure key vault
  - Creating k8s secret with cert

### CODE REVIEW

**Comment by florianrusch-zf** [comment]
@DominikPinsel @denisneuling does someone of you know if the dataplane also needs access to the vault?

**Comment by denisneuling** [comment]
@florianrusch-zf Afaik control- and dataplane share secrets via a common vault, so yes, the dataplane also needs access to the same vault.

Since we're already working on an open source vault implementation (which will replace the Azure KeVault) - Do you think this patch is still needed?

<sub>Denis Neuling <denis.neuling@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by florianrusch-zf** [comment]
@denisneuling that's a good question! In my opinion, this extensions is a bit too late for the testing phase of Catena-X. For example ZF and (I think) BMW already have setup their EDC's.

The reason I added this is because some IT departments have restricted the access to Azure, so there is no possibility to use a secret for the authentication.

Additional, HashiCorp also allows cert based authentication (but I think more changes are needed here for that 🤔): https://www.vaultproject.io/docs/auth/cert

What do you think? Should we use this change anyway?

**Comment by florianrusch-zf** [comment]
Is no longer needed by ZF as we now use hashicorp vault

**Pull request closed without merging**
