### PR TITLE
Feature/cloud http data

### PR DESCRIPTION
**Pull request by lucian-torje-siemens**
## What this PR changes/adds

This extension is able to push data to cloud (e.g. AWS S3) upload presigned URLs.

## Why it does that

Achieve compatibility between EDC and AWS S3 upload presigned URLs.

## Further notes

Note that downloading is possible using the current HttpDataSource implementation, unfortunately HttpDataSink is not compatible with uploading to an AWS S3 upload presigned URL. 

## Linked Issue(s)

No issue created

## Checklist

- [ ] added appropriate tests?
- [ ] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [ ] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [ ] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

## Notify list
@sn0wcat
@kbData

### CODE REVIEW

**Comment by sn0wcat** [comment]
@ndr-brt it would probably make a lot of sense to do this in the upstream - make `method` and `additionalHeaders` configurable so that the sink can be configured for any type of pre-signed URL storage (e.g. azure, aws, ali object storage etc.), however, we had a sort of a mixed experience with the readiness of the upstream to accept contributions, therefore the way via catenax-ng seemed to be more feasible.

**Comment by sn0wcat** [comment]
here is a list of peculiarities different presigned-url object storages have:

- AWS - expects `PUT` Verb 
- AZURE - expects `PUT` Verb + `{ "x-ms-blob-type": "BlockBlob" }` Header
- ALI Object Storage - expects `PUT` Verb and the `{ "Content-Type": "application/octet-stream" }` in header 

therefore it makes sense to make HttpHeaders and Verb configurable.

**Comment by kbData** [comment]
> Couldn't this be proposed as an integration for the `dataplane-http` module on the upstream repository? It would be only a metter add on the `HttpDataSink` the `additionalHeaders` field, and make the `method` and the `contentType` configurable, if I'm not wrong

Technically this makes a lot of sense. Still, we would prefer to get this pull request accepted as a first step - in order to get the functionality into the catena network sooner (there is already pressure for it). As we know, it is much harder and taker longer to get the approval in the original EDC repo. So we would like to proceed in the following way:

1) get this pull request into the product-edc repo
2) prepare the generic extention for dataplane-http module as proposed by @ndr-brt and make a pull request in the upstream repository
3) when 2 ready, migrate 1 to 2 in catena

I hope this approach is fine.

**Comment by lucian-torje-siemens** [comment]
There is pull request in EDC -> https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/1510

**Comment by lucian-torje-siemens** [comment]
@ndr-brt could you please check gitguardian for details - I've rechecked and could not find the issue

**Comment by denisneuling** [comment]
Closing due to [PR 1510](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/1510) was merged to the upstream oos repositories main branch.

**Pull request closed without merging**
